imports:
    - { resource: '%vendor_dir%/symplify/easy-coding-standard/config/psr2.yml' }

services:
    SlevomatCodingStandard\Sniffs\Classes\ClassConstantVisibilitySniff:
    SlevomatCodingStandard\Sniffs\Commenting\EmptyCommentSniff:
    SlevomatCodingStandard\Sniffs\Commenting\InlineDocCommentDeclarationSniff:
    SlevomatCodingStandard\Sniffs\ControlStructures\DisallowEqualOperatorsSniff:
    SlevomatCodingStandard\Sniffs\ControlStructures\NewWithParenthesesSniff:
    SlevomatCodingStandard\Sniffs\Exceptions\DeadCatchSniff:
    SlevomatCodingStandard\Sniffs\Namespaces\AlphabeticallySortedUsesSniff:
    SlevomatCodingStandard\Sniffs\Namespaces\DisallowGroupUseSniff:
    SlevomatCodingStandard\Sniffs\Namespaces\FullyQualifiedClassNameInAnnotationSniff:
    SlevomatCodingStandard\Sniffs\Namespaces\FullyQualifiedGlobalConstantsSniff:
    SlevomatCodingStandard\Sniffs\Namespaces\FullyQualifiedGlobalFunctionsSniff:
    SlevomatCodingStandard\Sniffs\Namespaces\MultipleUsesPerLineSniff:
    SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff:
        searchAnnotations: 1
    SlevomatCodingStandard\Sniffs\Namespaces\UseDoesNotStartWithBackslashSniff:
    SlevomatCodingStandard\Sniffs\Namespaces\UseSpacingSniff:
        linesCountBeforeFirstUse: 1
        linesCountBetweenUseTypes: 0
        linesCountAfterLastUse: 1
    SlevomatCodingStandard\Sniffs\Types\EmptyLinesAroundTypeBracesSniff:
        linesCountAfterOpeningBrace: 0
        linesCountBeforeClosingBrace: 0
    SlevomatCodingStandard\Sniffs\TypeHints\LongTypeHintsSniff:
    SlevomatCodingStandard\Sniffs\TypeHints\NullableTypeForNullDefaultValueSniff:
    SlevomatCodingStandard\Sniffs\TypeHints\ParameterTypeHintSpacingSniff:
    SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSpacingSniff:
    SlevomatCodingStandard\Sniffs\TypeHints\TypeHintDeclarationSniff:
        enableEachParameterAndReturnInspection: 0

    NatePage\Standards\Sniffs\Arrays\ForbiddenArrayLongSyntaxSniff:
    NatePage\Standards\Sniffs\Arrays\ForbiddenArrayTrailingCommaSniff:
    NatePage\Standards\Sniffs\Classes\RequireStrictDeclarationSniff:
    NatePage\Standards\Sniffs\Classes\StrictDeclarationFormatSniff:
    NatePage\Standards\Sniffs\Commenting\DocCommentSpacingSniff:
    NatePage\Standards\Sniffs\Commenting\FunctionCommentSniff:
    NatePage\Standards\Sniffs\ControlStructures\NoElseSniff:
    NatePage\Standards\Sniffs\ControlStructures\NoNotOperatorSniff:
    NatePage\Standards\Sniffs\ControlStructures\YodaConditionSniff:
